name: CI

on:
  push:
    branches:
      - develop

env:
  node_version: "15.x"

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install JS dependencies
        id: install
        run: yarn install
        continue-on-error: true
      - name: Lint
        id: lint
        run: ls yarn.lock && NODE_ENV=testing yarn lint
        continue-on-error: true
      - uses: snow-actions/line-notify@v1.0.0
        with:
          access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
          message: |
            ${{ github.repository }} Lint failed
            By ${{ github.actor }} on ${{ github.ref }}
        if: steps.install.conclusion == 'failure' || steps.lint.conclusion == 'failure'

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install JS dependencies
        id: install
        run: yarn install
        continue-on-error: true
      - name: Test
        id: test
        run: ls yarn.lock && NODE_ENV=testing yarn test
        continue-on-error: true
      - uses: snow-actions/line-notify@v1.0.0
        with:
          access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
          message: |
            ${{ github.repository }} Test failed
            By ${{ github.actor }} on ${{ github.ref }}
        if: steps.install.conclusion == 'failure' || steps.test.conclusion == 'failure'
